### ISSUE TITLE
0.1.8 Doesn't generate an updated grub.cfg

### ISSUE THREAD

**Issue by caleb** [johnramsden/zedenv-grub#29] opened 2019-12-03 16:35 UTC
Hi,

I'm on Arch Linux and have been using zedenv for a few months on my system. Everything worked until I upgraded `zedenv-grub` to `0.1.8-alpha`.

Now when I run `zedenv create`/`zedenv activate` my `/boot/grub/grub.cfg` file isn't updated. The boot environment is created successfully, but I don't get the new BE in my boot menu.

I don't get any errors when I run `zedenv create` or `zedenv update` (even when run with `-v`), and when I run `grub-mkconfig` the section for `/etc/grub.d/05_zfs_linux.py` is empty.

I reverted back to the `0.1.7` package and running `zedenv create`/`zedenv activate` properly generates a new `/boot/grub/grub.cfg` file.

I don't know if there's something weird with my setup, but here is my pool and zedenv information:

**ZFS Pool**
```
[root@archlinux ~]# zfs list
NAME                                                                                 USED  AVAIL     REFER  MOUNTPOINT
zroot                                                                                141G   758G      176K  none
zroot/ROOT                                                                          46.0G   758G      176K  none
zroot/ROOT/5.2.10                                                                   1.83M   758G     9.41G  /
zroot/ROOT/5.3.0                                                                     356K   758G     11.1G  /
zroot/ROOT/5.3.10                                                                    526M   758G     14.5G  /
zroot/ROOT/5.3.11.1                                                                 11.9M   758G     15.1G  /
zroot/ROOT/5.3.12                                                                   2.52G   758G     16.2G  /
zroot/ROOT/5.3.12.1                                                                  205M   758G     15.7G  /
zroot/ROOT/5.3.13                                                                   11.8M   758G     16.0G  /
zroot/ROOT/5.3.5                                                                    19.3M   758G     12.5G  /
zroot/ROOT/5.3.6                                                                     251M   758G     14.7G  /
zroot/ROOT/5.3.7                                                                     173M   758G     14.5G  /
zroot/ROOT/5.3.8                                                                    10.4M   758G     13.9G  /
zroot/ROOT/5.4.1                                                                    42.0G   758G     16.0G  /
zroot/ROOT/current                                                                   117M   758G     9.11G  /
zroot/ROOT/default                                                                  72.9M   758G     2.68G  /
zroot/ROOT/gui                                                                      68.3M   758G     6.89G  /
zroot/ROOT/live                                                                     2.00M   758G     9.97G  /
zroot/ROOT/networking                                                               30.8M   758G     2.78G  /
zroot/boot                                                                          6.59M   758G      176K  none
zroot/boot/grub                                                                     6.42M   758G     6.42M  /boot/grub
zroot/data                                                                          94.3G   758G      176K  none
zroot/data/home                                                                     94.3G   758G     94.3G  /home
zroot/docker                                                                        1.03G   758G      520M  /var/lib/docker
zroot/docker/08cc9e0156998d3d9beaf290621d095cfb93978be60bfcc3740824ea02accadf       83.3M   758G     83.3M  legacy
zroot/docker/167e8393465c4330e306b09e4cf4f17917fcbc74046515c87c162eb2804932d7        299M   758G      493M  legacy
zroot/docker/3115e332421b0e4206a6d46e78819b192bc7d94510243cbadbf9922c57e1b309       12.3M   758G     94.0M  legacy
zroot/docker/3eb445fdbb21eaa87b8f1303cb7be0aece99b3141ffa46f00f1ac61ac66d497e        128K   758G      493M  legacy
zroot/docker/5283be08c9548dd9de318f6ceb791819090b65fc034c8f7aa1c19bb8c1621290        120K   758G      522M  legacy
zroot/docker/5283be08c9548dd9de318f6ceb791819090b65fc034c8f7aa1c19bb8c1621290-init   160K   758G      522M  legacy
zroot/docker/794a2a4d283463b8a7d8d6bf3dc3c8ae7a2be0b6a425a8a9be9379834905d36e       30.6M   758G      522M  legacy
zroot/docker/c4c62215f6d0d9c333d12d90642d5e52d13e067c4b7dfe51316d71928a6eb8fa        144K   758G      522M  legacy
zroot/docker/c80dbcd2403fa8095fcfb9912dfcc17df47b61d573a65edca2dc6e9abf1e8c02       91.6M   758G      196M  legacy
zroot/docker/ee08b45105211c934854c83e1b759b0a5939e72257fcac4322cd7b9a1a73e6e8       13.8M   758G      107M  legacy
```

**ZEDENV**
```
[root@archlinux ~]# zedenv list
Name        Active   Mountpoint   Creation              
default              -            Mon-Aug-26-15:19-2019 
networking           -            Mon-Aug-26-15:22-2019 
gui                  -            Mon-Aug-26-15:25-2019 
current              -            Mon-Aug-26-16:15-2019 
5.2.10               -            Thu-Aug-29-9:56-2019  
live                 -            Fri-Sep-20-9:24-2019  
5.3.0                -            Sun-Sep-22-7:03-2019  
5.3.5                -            Wed-Oct-9-14:57-2019  
5.3.6                -            Mon-Oct-14-22:13-2019 
5.3.7                -            Fri-Oct-18-15:44-2019 
5.3.8                -            Fri-Nov-1-13:55-2019  
5.3.10               -            Mon-Nov-11-12:28-2019 
5.3.11.1             -            Wed-Nov-13-14:58-2019 
5.3.12               -            Thu-Nov-21-9:46-2019  
5.3.12.1             -            Sun-Nov-24-16:02-2019 
5.3.13      N        /            Mon-Nov-25-12:14-2019 
5.4.1       R        -            Tue-Dec-3-10:55-2019  
```

**Comment by johnramsden** [comment] 2019-12-04 07:16
I think it _might_ be caused by https://github.com/johnramsden/zedenv-grub/blob/137eb72565a22057a49eb07282d709e74251f242/zedenv_grub/grub.py#L252 @mkessler001 do you know why this change was made?

EDIT: Never mind I see that specifically for the boot pool case.

**Comment by johnramsden** [comment] 2019-12-04 23:20
@caleb Could you provide the output from:

```
zedenv get
```

**Comment by caleb** [comment] 2019-12-04 23:21
Here you go:

```bash
❯ zedenv get
PROPERTY               VALUE  
org.zedenv:bootloader  grub   
```

**Comment by mkessler001** [comment] 2019-12-05 07:58
I would suggest to start with the following two settings (assuming your kernel and ramdisk files are stored **within** your ROOT datasets):

    ❯ zedenv set org.zedenv.grub:bootonzfs=true
    ❯ zedenv set org.zedenv.grub:boot=/boot

Afterwards, please post your output from `zedenv activate -v 5.3.12.1` (or any other boot environment).

**Comment by caleb** [comment] 2019-12-05 21:57
Okay, I upgraded back to 0.1.8, set those properties and rand that command:

```
❯ sudo zedenv activate -v 5.4.1
Activating Boot Environment: 5.4.1

Configuring boot environment bootloader with grub

Checking prop: 'org.zedenv.grub:boot'
org.zedenv.grub:boot=/boot.

Checking prop: 'org.zedenv.grub:bootonzfs'
org.zedenv.grub:bootonzfs=true.

Checking prop: 'org.zedenv.grub:grubsubdir'
Checking prop: 'org.zedenv.grub:simpleentries'
Property 'bootonzfs' is set to invalid value true, should be 'yes', 'no', '0', or '1'. Exiting.
```

I set the `org.zedenv.grub:bootonzfs` property to `yes`, and re-ran the `activate`:

```
❯ sudo zedenv set org.zedenv.grub:bootonzfs=yes
❯ sudo zedenv activate -v 5.4.1
Activating Boot Environment: 5.4.1

Configuring boot environment bootloader with grub

Checking prop: 'org.zedenv.grub:boot'
org.zedenv.grub:boot=/boot.

Checking prop: 'org.zedenv.grub:bootonzfs'
org.zedenv.grub:bootonzfs=yes.

Checking prop: 'org.zedenv.grub:grubsubdir'
Checking prop: 'org.zedenv.grub:simpleentries'
Using plugin grub

Boot environment 5.4.1 exists'

Disabled automount for zroot/ROOT/5.2.10

Disabled automount for zroot/ROOT/5.3.0

Disabled automount for zroot/ROOT/5.3.10

Disabled automount for zroot/ROOT/5.3.11.1

Disabled automount for zroot/ROOT/5.3.12

Disabled automount for zroot/ROOT/5.3.12.1

Disabled automount for zroot/ROOT/5.3.13

Disabled automount for zroot/ROOT/5.3.5

Disabled automount for zroot/ROOT/5.3.6

Disabled automount for zroot/ROOT/5.3.7

Disabled automount for zroot/ROOT/5.3.8

Disabled automount for zroot/ROOT/current

Disabled automount for zroot/ROOT/default

Disabled automount for zroot/ROOT/gui

Disabled automount for zroot/ROOT/live

Disabled automount for zroot/ROOT/networking

Creating Temporary working directory. No changes will be made until the end of the GRUB configuration.

Going over list [{'name': 'zroot/ROOT/default'}, {'name': 'zroot/ROOT/networking'}, {'name': 'zroot/ROOT/gui'}, {'name': 'zroot/ROOT/current'}, {'name': 'zroot/ROOT/5.2.10'}, {'name': 'zroot/ROOT/live'}, {'name': 'zroot/ROOT/5.3.0'}, {'name': 'zroot/ROOT/5.3.5'}, {'name': 'zroot/ROOT/5.3.6'}, {'name': 'zroot/ROOT/5.3.7'}, {'name': 'zroot/ROOT/5.3.8'}, {'name': 'zroot/ROOT/5.3.10'}, {'name': 'zroot/ROOT/5.3.11.1'}, {'name': 'zroot/ROOT/5.3.12'}, {'name': 'zroot/ROOT/5.3.12.1'}, {'name': 'zroot/ROOT/5.3.13'}, {'name': 'zroot/ROOT/5.4.1'}].

Tried to run grub 'post activate', not implemented.
```

EDIT: Running `grub-mkconfig` as root still produces a grub config without any boot environments (i.e. the `### BEGIN /etc/grub.d/05_zfs_linux.py ###` block is empty), if that's helpful information.

**Comment by mkessler001** [comment] 2019-12-06 16:33
Thanks for your feedback. I can reproduce this behavior on my PC and fixed it (partly) with #30.
Due to the reason that my system uses a separate boot pool for kernel files, John has to fix and test this for the other boot configurations.

Should be fixed soon :)

**Comment by mkessler001** [comment] 2019-12-08 19:20
Unfortunately, it was not your problem which was fixed with #30.
Your logfile indicates, that the call to `post activate` from the grub bootloader plugin fails.

So lets start with the check if `grub` is set for each boot environment.
It is not necessary to set the value explicit for each boot environment with `zfs set ...`, the value should be inherited from the parent (`rpool/root` in this case).

    ❯ zedenv get org.zedenv:bootloader
    rpool/root                   org.zedenv:bootloader  grub

    ❯ zedenv get org.zedenv:bootloader -r
    rpool/root                   org.zedenv:bootloader  grub
    rpool/root/5.3.0             org.zedenv:bootloader  grub
    ...

As your system worked fine before, I don't think that this is the problem.
Maybe some of your configuration files wasn't updated properly.
Have you tried to completely remove and reinstall `zedenv`, `zedenv-grub` and `pyzfscmds`?
If you do so, please remove the following files as well

  -  `/usr/local/bin/zedenv`
  - `/etc/grub.d/05_zfs_linux.py`

After reinstallation, please check the following two files:

    ❯ sha1sum /etc/grub.d/05_zfs_linux.py
    c14382d962faa6dbc6a35d4ca848338433c19033  /etc/grub.d/05_zfs_linux.py

    ❯ sha1sum {PYTHON_INSTALL_DIR}/zedenv_grub/grub.py
    c5010917511c9ba950fda2f0d5dc41e3594ec4bf {PYTHON_INSTALL_DIR}/zedenv_grub/grub.py

If the error still exists, please post your output when calling `05_zfs_linux.py`:

    ❯ sudo python /etc/grub.d/05_zfs_linux.py
    ...

**Comment by johnramsden** [comment] 2019-12-08 20:29
I don't think is your configuration, I can confirm the same behavior on a fresh install with 0.1.8 grub.

I'll be debugging this today.

**Comment by johnramsden** [comment] 2019-12-08 20:54
The issue is that the new version of `zedenv` that supports extra boot pools is only available in master, and even if you're not using them it expects a function to be there, I will upgrade the `zedenv` arch package and create a new release which should solve this problem

**Comment by caleb** [comment] 2019-12-08 21:38
Thanks!

**Comment by johnramsden** [comment] 2019-12-08 21:56
Created a new `zedenv` release, let me know if that fixes the issue for you after upgrading.

**Comment by caleb** [comment] 2019-12-09 02:31
@johnramsden That worked! Thanks to you and @mkessler001.

**Closed as completed** 2019-12-09 23:56 UTC
Labels: bug
